// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkfO7osW-zqU9eour9PfXlWBd9-nkNPHk',
    appId: '1:373142748445:web:31b7e94a7fe6678ec875f4',
    messagingSenderId: '373142748445',
    projectId: 'ecommerce-c6f72',
    authDomain: 'ecommerce-c6f72.firebaseapp.com',
    storageBucket: 'ecommerce-c6f72.appspot.com',
    measurementId: 'G-DD1F4NKPDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsv-_AMJP_ER2PX0ldcIy3BTq_tEzD0Ug',
    appId: '1:373142748445:android:bbcf5a56169bf500c875f4',
    messagingSenderId: '373142748445',
    projectId: 'ecommerce-c6f72',
    storageBucket: 'ecommerce-c6f72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFkCY39VOV0WG_KmxVAyzmaO0HEQb-Tks',
    appId: '1:373142748445:ios:8d1cc6d3b143060cc875f4',
    messagingSenderId: '373142748445',
    projectId: 'ecommerce-c6f72',
    storageBucket: 'ecommerce-c6f72.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFkCY39VOV0WG_KmxVAyzmaO0HEQb-Tks',
    appId: '1:373142748445:ios:8d1cc6d3b143060cc875f4',
    messagingSenderId: '373142748445',
    projectId: 'ecommerce-c6f72',
    storageBucket: 'ecommerce-c6f72.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkfO7osW-zqU9eour9PfXlWBd9-nkNPHk',
    appId: '1:373142748445:web:31b7e94a7fe6678ec875f4',
    messagingSenderId: '373142748445',
    projectId: 'ecommerce-c6f72',
    authDomain: 'ecommerce-c6f72.firebaseapp.com',
    storageBucket: 'ecommerce-c6f72.appspot.com',
    measurementId: 'G-DD1F4NKPDD',
  );
}
